global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using LLVMSharp.Interop;
global using Array = Moth.LLVM.Data.Array;
global using EnumDecl = Moth.LLVM.Data.EnumDecl;
global using Function = Moth.LLVM.Data.Function;
global using GlobalVariable = Moth.LLVM.Data.GlobalVariable;
global using Index = ClangSharp.Index;
global using Parameter = Moth.LLVM.Data.Parameter;
global using Pointer = Moth.LLVM.Data.Pointer;
global using StructDecl = Moth.LLVM.Data.StructDecl;
global using SystemType = System.Type;
global using TraitDecl = Moth.LLVM.Data.TraitDecl;
global using Type = Moth.LLVM.Data.Type;
global using TypeDecl = Moth.LLVM.Data.TypeDecl;
global using Value = Moth.LLVM.Data.Value;
global using Version = Moth.LLVM.Metadata.Version;
global using Void = Moth.LLVM.Data.Void;
